# 该配置的名称是固定的，不可以改变，否则将不能自动加载到数据源中
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springt4?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: mc
    password: 123456

  application:
    name: spring-t # 注册到eureka server的服务名
